# Dockerfile or Containerfile, the name doesn't matter.
# This dockerfile compiles the modules using the builder, and puts it in the production
# The stage name should be lowercase according to StageNameCasing (https://docs.docker.com/reference/build-checks/stage-name-casing/).
FROM docker.io/library/nginx:mainline AS builder

# Step 1.
# --- Compiling and Installing Coraza for NGINX Open Source ---

WORKDIR /usr/src/

# Install the dependency
RUN apt-get update && \
apt-get install -y \
curl \
jq \
tar \
wget \
git \
golang \
gcc \
make \
libc6-dev \
libtool \
libpcre2-dev \
zlib1g-dev \
libssl-dev \
ca-certificates

### 1. Download and build https://github.com/corazawaf/libcoraza
RUN git clone --depth 1 --single-branch https://github.com/corazawaf/libcoraza.git /usr/src/libcoraza
WORKDIR /usr/src/libcoraza
RUN ./build.sh &&\
./configure --prefix=/usr/local &&\
make -j$(nproc) &&\
make install

# 2. Download https://github.com/corazawaf/coraza-nginx
WORKDIR /usr/src/

RUN curl -fsSL https://api.github.com/repos/corazawaf/coraza-nginx/releases/latest |\
jq -r '.tarball_url' |\
wget -O __latest_coraza-nginx_releases.tar.gz -i - &&\
mkdir -p /usr/src/coraza-nginx &&\
tar -xf __latest_coraza-nginx_releases.tar.gz  -C /usr/src/coraza-nginx/ --strip-components=1

### Download and Compile the lua modules
# Doc: https://github.com/openresty/lua-nginx-module#installation

WORKDIR /usr/src/

# 1. Download and build https://github.com/openresty/luajit2
RUN git clone --depth 1 -b v2.1-agentzh --single-branch https://github.com/openresty/luajit2.git /usr/src/luajit2 

WORKDIR /usr/src/luajit2

RUN make -j$(nproc) && make install

# 2. Download https://github.com/vision5/ngx_devel_kit
WORKDIR /usr/src/

RUN curl -fsSL https://api.github.com/repos/vision5/ngx_devel_kit/releases/latest |\
jq -r '.tarball_url' |\
wget -O __latest_ngx_devel_kit_releases.tar.gz -i - &&\
mkdir -p /usr/src/ngx_devel_kit &&\
tar -xf __latest_ngx_devel_kit_releases.tar.gz  -C /usr/src/ngx_devel_kit/ --strip-components=1

# 3. Download https://github.com/openresty/lua-nginx-module
WORKDIR /usr/src/

RUN git clone --depth 1 --single-branch https://github.com/openresty/lua-nginx-module.git /usr/src/lua-nginx-module/

# 4. Download https://github.com/openresty/lua-resty-core and https://github.com/openresty/lua-resty-lrucache
WORKDIR /usr/src/

RUN git clone --depth 1 --single-branch https://github.com/openresty/lua-resty-core.git /usr/src/lua-resty-core

WORKDIR /usr/src/lua-resty-core

RUN make install PREFIX=/opt/nginx

RUN git clone --depth 1 --single-branch https://github.com/openresty/lua-resty-lrucache.git /usr/src/lua-resty-lrucache

WORKDIR /usr/src/lua-resty-lrucache

RUN make install PREFIX=/opt/nginx

# 5. Tell nginx's build system where to find LuaJIT 2.1 and more:
ENV LUAJIT_LIB=/usr/local/lib
ENV LUAJIT_INC=/usr/local/include/luajit-2.1

### Download https://github.com/openresty/headers-more-nginx-module
WORKDIR /usr/src/

RUN git clone --depth 1 --single-branch https://github.com/openresty/headers-more-nginx-module.git /usr/src/headers-more-nginx-module

### Download Nginx and build the modules
WORKDIR /usr/src/
RUN wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz -O __my_nginx_releases.tar.gz &&\
mkdir -p /usr/src/nginx/ &&\
tar -xf __my_nginx_releases.tar.gz -C /usr/src/nginx/ --strip-components=1

WORKDIR /usr/src/nginx

RUN ./configure --with-compat \
--prefix=/usr/local \
# Crowdsec needs this to enable lua_ssl_trusted_certificate and others
--with-http_ssl_module \
--add-dynamic-module=/usr/src/coraza-nginx/ \
--add-dynamic-module=/usr/src/ngx_devel_kit/ \
--add-dynamic-module=/usr/src/lua-nginx-module/ \
--add-dynamic-module=/usr/src/headers-more-nginx-module/ &&\
make -j$(nproc) modules

### Download and Install crowdsec-nginx-bouncer and its dependency
# 1. Download and Install https://github.com/ledgetech/lua-resty-http/

WORKDIR /usr/src/

RUN curl -fsSL https://api.github.com/repos/ledgetech/lua-resty-http/releases/latest |\
jq -r '.tarball_url' |\
wget -O __latest_lua-resty-http_releases.tar.gz -i - &&\
mkdir -p /usr/src/lua-resty-http &&\
tar -xf __latest_lua-resty-http_releases.tar.gz  -C /usr/src/lua-resty-http --strip-components=1

WORKDIR /usr/src/lua-resty-http

RUN make install PREFIX=/opt/nginx

# 1.1 Download and Install https://github.com/ledgetech/lua-resty-http/'s dependency https://github.com/openresty/lua-resty-string

RUN git clone --depth 1 --single-branch https://github.com/openresty/lua-resty-string /usr/src/lua-resty-string

WORKDIR /usr/src/lua-resty-string

RUN make install PREFIX=/opt/nginx

# 1.2 Download and Install https://github.com/ledgetech/lua-resty-http/'s dependency https://github.com/fffonion/lua-resty-openssl

RUN git clone --depth 1 --single-branch https://github.com/fffonion/lua-resty-openssl /usr/src/lua-resty-openssl

WORKDIR /usr/src/lua-resty-openssl

RUN make install PREFIX=/opt/nginx

# 2. Download and Compile https://github.com/mpx/lua-cjson

RUN git clone --depth 1 --single-branch https://github.com/openresty/lua-cjson/ /usr/src/lua-cjson

WORKDIR /usr/src/lua-cjson
# I can't just change the PREFIX because I will copy all the file to /usr/local in the production stage
RUN make LUA_VERSION=5.1 \
CFLAGS="-O3 -Wall -pedantic -DNDEBUG -I/usr/local/include/luajit-2.1" \
PREFIX="/usr/local" &&\
make install

# 3. The crowdsec boucner

RUN curl -fsSL https://api.github.com/repos/crowdsecurity/cs-nginx-bouncer/releases/latest |\
jq -r '.assets[0].browser_download_url' |\
wget -O __latest_cs-nginx-bouncer_releases.tar.gz -i - &&\
mkdir -p /usr/src/cs-nginx-bouncer &&\
tar -xf __latest_cs-nginx-bouncer_releases.tar.gz  -C /usr/src/cs-nginx-bouncer/ --strip-components=1

# Remove the lua_package_path because we will declaration the modules in nginx.conf, else error: nginx: [emerg] "lua_package_path" directive is duplicate in /etc/nginx/nginx.conf:38
RUN sed -i "/^lua_package_path/d" /usr/src/cs-nginx-bouncer/nginx/crowdsec_nginx.conf

### Copy the compiled files

FROM docker.io/library/nginx:mainline AS production

# Copy the nginx dynamic modules (.so) files

COPY --from=builder /usr/src/nginx/objs/ndk_http_module.so /etc/nginx/modules/ndk_http_module.so
COPY --from=builder /usr/src/nginx/objs/ngx_http_coraza_module.so /etc/nginx/modules/ngx_http_coraza_module.so
COPY --from=builder /usr/src/nginx/objs/ngx_http_headers_more_filter_module.so /etc/nginx/modules/ngx_http_headers_more_filter_module.so
COPY --from=builder /usr/src/nginx/objs/ngx_http_lua_module.so /etc/nginx/modules/ngx_http_lua_module.so

# Copy the dependency of the nginx nginx dynamic modules

COPY --from=builder /opt/nginx/ /opt/nginx
COPY --from=builder /usr/local/lib/libcoraza.so /usr/local/lib/libcoraza.so
COPY --from=builder /usr/local/lib/libluajit-5.1.so* /usr/local/lib/

# Copy the crowdsec-nginx-bouncer's dependency

COPY --from=builder /usr/local/lib/lua/5.1/cjson.so /usr/local/lib/lua/5.1/cjson.so

# Copy the crowdsec-nginx-bouncer
# Refer to https://github.com/crowdsecurity/cs-nginx-bouncer/blob/main/install.sh
# The user should handle /etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf file on there own in the crowdsec image.
ARG LIB_PATH="/usr/local/lua/crowdsec/"
ARG DATA_PATH="/var/lib/crowdsec/lua/"
RUN mkdir -p ${LIB_PATH}/plugins/crowdsec/ &&\
mkdir -p ${DATA_PATH}/templates/
COPY --from=builder /usr/src/cs-nginx-bouncer/nginx/crowdsec_nginx.conf /etc/nginx/conf.d/crowdsec_nginx.conf
COPY --from=builder /usr/src/cs-nginx-bouncer/lua-mod/lib ${LIB_PATH}
COPY --from=builder /usr/src/cs-nginx-bouncer/lua-mod/templates/ ${DATA_PATH}/templates/

# Copy the ca-certificates because crowdsec needs it.
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

# Fresh .so file cache
RUN ldconfig
